import type { Visibility } from './common';

export type PostType =
  | 'free_speech'
  | 'request'
  | 'quest_log'         // 📘 Logs documenting quest progress (child of node)
  | 'quest_task'        // ✅ Tasks or objectives inside a quest node
  | 'meta_system'       // 🧠 Internal system post
  | 'meta_announcement'; // 📣 Public system broadcast (e.g. platform changelog)

export type PostTag =
  | 'ai'
  | 'feedback'
  | 'story'
  | 'system'
  | 'bug'
  | 'progress'
  | 'event'
  | 'release'
  | 'repost'
  | string; // fallback for custom tags

export interface Post {
  id: string;

  /** User who created the post */
  authorId: string;

  /** Type of post used to infer layout, routing, and interaction */
  type: PostType;

  /** Markdown or plain text content */
  content: string;

  /** Visibility level, used for access and filtering */
  visibility: Visibility;

  /** Timestamp in ISO format */
  timestamp: string;

  /** Optional: ISO timestamp alias for sorting if needed */
  createdAt?: string;

  /** Optional: The quest this post is linked to (as log or task) */
  questId?: string | null;

  /** Optional: Logical node within the quest (used for graph layout + sorting) */
  nodeId?: string;

  /** Optional: The quest name (for display in title formatting) */
  questName?: string;

  /** Hashtags or topic tags */
  tags: PostTag[];

  /** Other users invited to collaborate on this post */
  collaborators: string[];

  /** If this post is a reply to another post */
  replyTo?: string | null;

  /** If this post is a repost of another post */
  repostedFrom?: RepostMeta | null;

  /** Items linked to this post (quests, posts, or boards) */
  linkedItems: LinkedItem[];

  /** Reactions grouped by type and userId */
  reactions?: ReactionSet;

  /** If auto-generated by the system */
  systemGenerated?: boolean;

  /** Reason or origin for auto-generation (e.g. 'linked_to_quest', 'repost', 'merge') */
  autoGeneratedReason?: string;
}

export interface LinkedItem {
  itemId: string;
  itemType: 'quest' | 'post' | 'board';
  nodeId?: string; // Quest-specific node context (e.g., for maps or structure)
}

export interface RepostMeta {
  originalPostId: string;
  username: string;
  originalContent: string;
  originalTimestamp: string;
}

export interface ReactionSet {
  like?: Record<string, string>;   // userId: timestamp
  love?: Record<string, string>;
  repost?: Record<string, string>;
}