import type { Visibility } from './common';
import type { LinkedItem } from './itemTypes';

/**
 * Supported types of posts used throughout the system.
 */
export type PostType =
  | 'free_speech'
  | 'request'
  | 'log'
  | 'task'
  | 'quest'
  | 'meta_system'
  | 'meta_announcement'
  | 'commit'
  | 'issue'
  | 'solved';
  
/**
 * Supported tags for labeling and filtering posts.
 */
export type PostTag =
  | 'ai'
  | 'feedback'
  | 'story'
  | 'system'
  | 'bug'
  | 'progress'
  | 'event'
  | 'release'
  | 'repost'
  | 'quest'
  | string;

/**
 * Optional task progress label for posts in quest boards.
 */
export type QuestTaskStatus = 'To Do' | 'In Progress' | 'Blocked' | 'Done' | string;

/**
 * Base post structure used across the platform.
 */
export interface Post {
  id: string;

  authorId: string;
  author?: {
    id: string;
    username?: string;
  };

  type: PostType;
  content: string;
  visibility: Visibility;
  timestamp: string;
  createdAt?: string;

  questId?: string | null;
  questNodeTitle?: string;
  nodeId?: string;

  tags: PostTag[];
  status?: QuestTaskStatus;
  collaborators: CollaberatorRoles[];

  replyTo?: string | null;
  repostedFrom?: RepostMeta | null;
  linkedItems: LinkedItem[];

  reactions?: ReactionSet;
  reactionCounts?: ReactionCountMap;

  systemGenerated?: boolean;
  autoGeneratedReason?: string;

  enriched?: boolean;

  /** Commit-style enhancements */
  linkedNodeId?: string;         // link to file or code node
  gitDiff?: string;              // unified diff format (commit or patch)
  commitSummary?: string;        // short summary for commit-type posts
}

/**
 * Users associated with a post.
 */
export interface CollaberatorRoles {
  userId: string;
  username?: string;
  roles?: string[];
}

/**
 * Repost metadata.
 */
export interface RepostMeta {
  originalPostId: string;
  username?: string;
  originalContent: string;
  originalTimestamp: string;
}

/**
 * Supported reaction types.
 */
export type ReactionType = 'like' | 'heart' | 'repost';

/**
 * Count of reactions by type.
 */
export type ReactionCountMap = Record<ReactionType, number>;

/**
 * Raw user reactions.
 */
export interface ReactionSet {
  like?: Record<string, string>;
  love?: Record<string, string>;
  repost?: Record<string, string>;
}

/**
 * Optional log event in user timeline (e.g., “posted a quest”).
 */
export interface TimelineEvent {
  userId: string;
  type: string;
  content: string;
}

/**
 * Extended post format for rendering, editing, and UI previews.
 */
export interface EnrichedPost extends Post {
  enrichedCollaborators?: Array<{
    userId: string;
    username?: string;
    roles?: string[];
    avatarUrl?: string;
    bio?: string;
  }>;

  renderedContent?: string;

  mediaPreviews?: Array<{
    url: string;
    type: 'image' | 'video' | 'embed' | 'file';
    title?: string;
    thumbnail?: string;
  }>;

  quotedPost?: Post;
  originalEnrichedPost?: EnrichedPost;
}
