name: CI
on:
  pull_request:
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd ethos-backend
          npm ci
      - name: Type check
        run: |
          cd ethos-backend
          npx tsc --noEmit
      - name: Run tests
        run: |
          cd ethos-backend
          npm test -- -w=1
      - name: Lint & build frontend
        run: |
          cd ethos-frontend
          npm ci
          npm run lint
          npm run build
