name: CI
on:
  pull_request:
jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        run: ./setup.sh
      - name: Apply Prisma migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
          cd ethos-backend
          npx prisma migrate deploy
      - name: Type check backend
        run: |
          cd ethos-backend
          tsc -p tsconfig.json
      - name: Type check frontend
        run: |
          cd ethos-frontend
          tsc -p tsconfig.json
      - name: Run backend and migration tests
        run: |
          cd ethos-backend
          npm test -- -w=1
      - name: Lint, test & build frontend
        run: |
          cd ethos-frontend
          npm run lint
          npm test -- -w=1
          npm run build
