name: CI
on:
  pull_request:
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        run: ./setup.sh
      - name: Type check backend
        run: |
          cd ethos-backend
          tsc -p tsconfig.json
      - name: Type check frontend
        run: npx tsc -p ethos-frontend/tsconfig.json
      - name: Run backend tests
        run: |
          cd ethos-backend
          npm test -- -w=1
      - name: Lint, test & build frontend
        run: |
          cd ethos-frontend
          npm run lint
          npm test -- -w=1
          npm run build
